#!/bin/sh
# Author: Caleb Stewart
# URL: https://github.com/calebstewart/swaycwd.git
# Description: print the CWD of the currently focused window in swaywm

# Find the PID of the process
PID=$(
    swaymsg -t get_tree |
        jq -r '.. | select(.pid? and .focused?) | .pid'
)

# how far down does the rabbit hole go? D:
while pgrep -P "$PID" >/dev/null; do
  PID=$(pgrep -P "$PID" | tail -n1)
done

# Show the current working directory
readlink -e "/proc/$PID/cwd"
